# Generated by Django 4.1.3 on 2023-02-10 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=2000)),
                ('sharing', models.BooleanField()),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('OH', 'Owner house'), ('RH', 'Roser house')], max_length=2)),
                ('begin_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('pricing', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('creation_date', models.CharField(max_length=255)),
                ('id_roser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Plant_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.plant')),
                ('id_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('rating', models.SmallIntegerField()),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.person')),
            ],
        ),
    ]
