# Generated by Django 4.1.3 on 2023-02-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant_reservation',
            old_name='id_plant',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='plant_reservation',
            old_name='id_reservation',
            new_name='reservation',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id_owner',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='id_owner',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id_roser',
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='backendapp.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='roser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments_written', to='backendapp.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='backendapp.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='roser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_made', to='backendapp.person'),
            preserve_default=False,
        ),
    ]
