# Generated by Django 4.1.6 on 2023-03-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_rename_id_plant_plant_reservation_plant_and_more'),
        ('backendapp', '0003_update_varchar_length_plant'),
    ]

    operations = [
    ]
