# Generated by Django 4.1.6 on 2023-03-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_merge_20230301_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='picture',
            field=models.TextField(),
        ),
    ]
