# Generated by Django 4.1.6 on 2023-03-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_alter_plant_picture'),
    ]

    operations = [        
        migrations.CreateModel(
            name='Person_salt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.person')),
                ('sel', models.CharField(max_length=255)),
            ],
        ),
    ]
