# Generated by Django 4.1.6 on 2023-07-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_create_user_salt_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('date_envoie', models.CharField(max_length=255)),
                ('id_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='backendapp.plant')),
                ('id_roser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_written', to='backendapp.person')),
            ],
        ),
        migrations.RenameField(
            model_name='person_salt',
            old_name='person',
            new_name='person_id',
        ),
        migrations.RenameField(
            model_name='person_salt',
            old_name='sel',
            new_name='salt',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
