# Generated by Django 4.1.6 on 2023-07-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0007_message_rename_person_person_salt_person_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_salt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
